### PR TITLE
feat: support for msg undelegate

### PR DESCRIPTION
**Pull request by foxpy**

### CODE REVIEW

**Review by ratik — APPROVED** [review]

**Review by sotnikov-s — APPROVED** [review]

**Comment by pr0n00gler** [comment]
Why do we need `MsgUndelegate` (and `MsgDelegate`) in the neutronjsplus?

**Comment by foxpy** [comment]
> Why do we need `MsgUndelegate` (and `MsgDelegate`) in the neutronjsplus? Neutron doesn't have staking module

well, `MsgDelegate` was already implemented before, hence I decided to add `MsgUndelegate` as well.

Should I remove both now? I will have to patch all integration tests though.

**Comment by pr0n00gler** [comment]
> > Why do we need `MsgUndelegate` (and `MsgDelegate`) in the neutronjsplus? Neutron doesn't have staking module
> 
> well, `MsgDelegate` was already implemented before, hence I decided to add `MsgUndelegate` as well.
> 
> Should I remove both now? I will have to patch all integration tests though.

Ideally yes

**Comment by foxpy** [comment]
Superseded by #19

**Pull request closed without merging**
